### PR TITLE
New ATM textures

### PR DESCRIPTION
**Pull request by El-Naso**
Replaced the original ATM textures with my own. I think you guys will like these :D

### CODE REVIEW

**Comment by SwissalpS** [comment]
works for me.
@El-Naso would it be ugly to continue the stripes on WT around to front 1-2 pixels each side?
They wouldn't need to be solid, they could be mixed with background.
I'm asking this because mk1 atm and WT looks identical from the front, the side that is mostly not built around.
(Yes mk1 is hardly used, still think it would be nice if they were recognizable without having to interact with them)

**Comment by El-Naso** [comment]
@SwissalpS ~~if WT had it's own unique front and top textures I could make it work somehow, probably.~~

**Comment by SwissalpS** [comment]
I can help you out with the needed code if that is what is stopping you :D
It would be great if all of them were recognizable from at least the front.

**Comment by El-Naso** [comment]
actually, I just checked and the code does reference texture files for WT front and top. I could just adjust the color of every face, that way it would be unique enough.

**Comment by SwissalpS** [comment]
well, the top is currently shared between mk1 and wt. But I think we can add another 16x16 file :D

**Comment by El-Naso** [comment]
That would certainly make things easier :D

**Comment by El-Naso** [comment]
now a question: should I add those textures to the main branch of the fork I made, does that update this PR or should the PR be removed?

**Comment by SwissalpS** [comment]
yes, adding commits to the branch you submited as PR (El-Naso:master) adds them to the PR

**Comment by SwissalpS** [comment]
and hopefully 6r1d will squash when merging so the texture changes only go once into the .git history

**Comment by El-Naso** [comment]
Your original idea of making the strips wrap around a bit [looks pretty good](https://cdn.discordapp.com/attachments/679038692668735498/940675448432640040/screenshot_20220208_152318.jpg) :D

**Comment by SwissalpS** [comment]
+1 approval

**Comment by BuckarooBanzay** [comment]
@6r1d ^
could this repo possibly be moved to the `mt-mods` org?

**Comment by 6r1d** [comment]
Sorry about the delay, and done.

**Comment by BuckarooBanzay** [comment]
> Sorry about the delay, and done.

Thank you :heart:

**Pull request merged**
